# Generated by Django 2.2.5 on 2020-08-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
